"""rename users_to_chats and title for chat

Revision ID: 0a7ba43943cb
Revises: cbfccdb41280
Create Date: 2026-06-05 00:11:29.961497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7ba43943cb'
down_revision: Union[str, Sequence[str], None] = 'cbfccdb41280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_member',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=16), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.drop_table('users_to_chats')
    op.execute('DELETE FROM chat')
    op.add_column('chat', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'title')
    op.create_table('users_to_chats',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_registered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('users_to_chats_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('users_to_chats_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name=op.f('users_to_chats_pkey'))
    )
    op.drop_table('chat_member')
    # ### end Alembic commands ###
