from typing import Protocol
from domain import Base

class TransactionAlchemyManagerProtocol(Protocol):
    async def commit(self) -> None: ... 
    async def flush(self) -> None: ...
    async def save(self, model: Base) -> None: ...
    async def delete(self, model: Base) -> None: ...