from typing import Protocol
from callerbot.infrastructure.database.models import Base


class UoWProtocol(Protocol):
    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def add(self, model: Base) -> None: ...
    async def delete(self, model: Base) -> None: ...
